version: '3.0' 
services:
 elasticsearch:
  image: elasticsearch:8.7.0
  restart: always 
  container_name: elasticsearch
  volumes:
   - /usr/local/soft/docker/elasticsearch/data:/usr/share/elasticsearch/data \
   - /usr/local/soft/docker/elasticsearch/plugins:/usr/share/elasticsearch/plugins
  environment:
    discovery.type=single-node
  ports:
    - '9200:9200'  
    - '9300:9300'
  privileged: true
