version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    restart: always
    container_name: jenkins
    environment:
      - TZ="Asia/Shanghai"
    ports:
      - 9101:8080
      - 50000:50000
    volumes:
      - /usr/local/soft/jenkins:/var/jenkins_home
      - /usr/local/soft/apache-maven-3.6.1:/usr/local/maven
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
    privileged: true
