version : '3'
services:
  nginx:
    container_name: nginx
    restart: always
    image: nginx
    ports:
      - "80:80"
    volumes:
      # 挂载nginx.conf配置文件
      - /usr/local/soft/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      # 挂载nginx配置文件
      - /usr/local/soft/nginx/conf/conf.d:/etc/nginx/conf.d
      # 挂载nginx日志文件
      - /usr/local/soft/nginx/logs:/var/log/nginx
      # 挂载nginx内容
      - /usr/local/soft/nginx/html:/usr/share/nginx/html
