version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.10.5
    container_name: rabbitmq
    restart: always
    hostname: myRabbitmq
    volumes:
      - /usr/local/soft/rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
    ports: 
     - 5672:5672
     - 15672:15672
