version: '3'
services:
  sonarqube:
    image: sonarqube:9.6.1-community
    container_name: sonarqube
    restart: always
    volumes:
      - /usr/local/soft/sonarqube/extensions:/opt/sonarqube/extensions
      - /usr/local/soft/sonarqube/data:/opt/sonarqube/data
      - /usr/local/soft/sonarqube/logs:/opt/sonarqube/logs
    environment:
      - sonar.jdbc.url=jdbc:postgresql://192.168.1.107:5432/sonar
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=123456
      - COMPOSE_PROJECT_NAME:sonarqube-server
    ports: 
     - 9000:9000
