version: "3"
services:
  sqlserver-2019:
    restart: always
    #容器名称
    container_name: sqlserver2019
    #镜像名称
    image: mcr.microsoft.com/mssql/server:2019-latest
    #端口映射
    ports:
      - 1433:1433
    #挂载
    volumes:
      - /home/docker/sqlserver:/var/opt/mssql
    #环境变量
    environment:
      ACCEPT_EULA=Y
      #SA用户密码长度必须至少为 8 个字符，并包含以下四组中的三组字符：大写字母、小写字母、10 位基数和符号
      SA_PASSWORD=Dasasdfng3d1!@# #自己设置密码
