version: '3.3'
services:
  redis_exporter:
    image: oliver006/redis_exporter
    container_name: redis_exporter
    restart: always
    environment:
      REDIS_ADDR: "192.168.31.100:6379"
      REDIS_PASSWORD: 123456
    ports:
      - "9121:9121"